catalog_movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('movie/', include("movie.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name = "movie"
urlpatterns = [
    path("", views.index, name="index" ),
    path("dashboard/", views.my_dashboard, name="dashboard"),
    path("login/", views.my_login, name="login"),
    path("user_login/", views.user_login, name="user_login"),
    path("user_logout/", views.user_logout, name="logout"),
    
    path("genre_list/", views.genre_list_view, name="genre_list"),
    path("actors_list/", views.actor_list_view, name="actors_list"),
    path("movie_list/", views.movie_list_view, name="movie_list"),
    
    path("movie_form/", views.movie_form, name="movie_form"),
    path("genre_form/", views.genre_form, name="genre_form"),
    path("actor_form/", views.actor_form, name="actor_form"),

    path("genre_save/", views.genre_save, name="genre_save"),
    path("movie_save/", views.movie_save, name="movie_save"),
    path("actor_save/", views.actor_save, name="actor_save"),
    
    path('genre/<int:genre_id>/', views.movies_by_genre, name='movies_by_genre'),
    path('actor/<int:actor_id>/', views.movies_by_actor, name='movies_by_actor'),
    
    path("search_list_view/", views.search_list_view, name="search_list_view"),
    
    path('movie/<int:movie_id>/', views.movie_detail_view, name='movie_detail'),
    
    path('movie/<int:movie_id>/like/', views.like_movie, name='like_movie'),
    path('movie/<int:movie_id>/dislike/', views.dislike_movie, name='dislike_movie'),
    
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
class Actor(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Movie(models.Model):
    name = models.CharField(max_length=100)
    synopsis = models.CharField(max_length=250)
    duration = models.IntegerField()
    year = models.IntegerField()
    imdb = models.FloatField()
    trailerLink = models.CharField(max_length=250)
  
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class RateMovieUser(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reaction = models.CharField(max_length=10, choices=[('like', 'Like'), ('dislike', 'Dislike')])
    
    class Meta:
        unique_together = ('user', 'movie')

    def __str__(self):
        return f"{self.user.username} - {self.movie.name} - {self.reaction}"

class ActorMovie(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

class TagMovie(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

class Image(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    

movie/views.py
from django.shortcuts import render

# Create your views here.

movie/views/view_actors.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Actor

@login_required
def actor_form(request):
    return render(request, 'movie/actor_form.html')

def actor_list_view(request):
    actors = Actor.objects.all()
    data = set_data("actors", actors)
    return render(request, 'movie/actor_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

@login_required
def actor_save(request):
    name = request.POST['name']
    last_name = request.POST['last_name']
    age = request.POST['age']
    actor = Actor(name=name, last_name=last_name, age=age)
    actor.save()

    return redirect("movie:actors_list")

movie/views/view_genre.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Genre

@login_required
def genre_form(request):
    return render(request, 'movie/genre_form.html')

@login_required
def genre_save(request):
    name = request.POST['name']
    genre = Genre(name=name)
    genre.save()

    return redirect("movie:genre_list")

def genre_list_view(request):
    genres = Genre.objects.all()
    data = set_data("genres", genres)
    return render(request, 'movie/genre_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

movie/views/view_login.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count, Q
from ..models import Movie, Genre, Actor, RateMovieUser

def my_login(request):
    return render(request, 'movie/login.html')

def my_dashboard(request):
    return render(request, 'movie/dashboard.html')

def user_login(request):
    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect("movie:index")
    else:
        context = {
            "error_message": "Nombre de usuario o contraseña incorrectos."
        }
        return render(request, 'movie:login', context)

def user_logout(request):
    logout(request)
    return redirect('movie:index')

def index(request):
    movies = (Movie.objects
              .prefetch_related('genre', 'actormovie_set', 'image_set')
              .annotate(
                  like_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='like')),
                  dislike_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='dislike'))
              )
              .all())
    genres = Genre.objects.all()
    actors = Actor.objects.all()
    user_reactions=[]
    if request.user.is_authenticated:
     user_reactions = {reaction.movie.id: reaction.reaction for reaction in RateMovieUser.objects.filter(user=request.user)}
    
    context = {
        'genres': genres,
        'movies': movies,
        'actors': actors,
        'user_reactions': user_reactions,
    }
    return render(request, 'movie/index.html',context)

def movie_list_view(request):
    movies = (Movie.objects
              .prefetch_related('genre', 'actormovie_set', 'image_set')
              .annotate(like_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='like')))
              .all())
    genres = Genre.objects.all()

    context = {
        'movies': movies,
        'genres': genres,
    }
    return render(request, 'movie/movie_list.html', context)

def movies_by_genre(request, genre_id):
    genre = Genre.objects.get(id=genre_id)
    movies = Movie.objects.filter(genre=genre)

    context = {
        'genre': genre,
        'movies': movies,
    }
    return render(request, 'movie/movies_by_genre.html', context)

def movies_by_actor(request, actor_id):
    actor = Actor.objects.get(id=actor_id)
    movies = Movie.objects.filter(actormovie__actor=actor)

    context = {
        'actor': actor,
        'movies': movies,
    }
    return render(request, 'movie/movies_by_actor.html', context)

def movie_detail_view(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    images = movie.image_set.all()
    actors = movie.actormovie_set.all()

    context = {
        'movie': movie,
        'images': images,
        'actors': actors,
    }

    return render(request, 'movie/movie_detail.html', context)

def like_movie(request, movie_id):
    if request.method == 'POST':
        movie = get_object_or_404(Movie, id=movie_id)
        RateMovieUser.objects.update_or_create(
            user=request.user,
            movie=movie,
            defaults={'reaction': 'like'}
        )
    return redirect('movie:index')

def dislike_movie(request, movie_id):
    if request.method == 'POST':
        movie = get_object_or_404(Movie, id=movie_id)
        RateMovieUser.objects.update_or_create(
            user=request.user,
            movie=movie,
            defaults={'reaction': 'dislike'}
        )
    return redirect('movie:index')

movie/views/view_movies.py
from django.shortcuts import render
from django import forms
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Movie, Genre, Image, Actor, ActorMovie

def movies(request):
    movies = Movie.objects.all()
    
    context = {
        "movies": movies
    }
    
    return (render, "movie/movies", context)

@login_required
def save_movie(request):
    return redirect("movie:index")

@login_required
def movie_form(request):
    genres = Genre.objects.all()
    actors = Actor.objects.all() 
    
    context = {
        "genre_list" : genres,
        "actor_list": actors
    }

    return render(request, 'movie/movie_form.html', context)

def movie_list_view(request):
    movies = Movie.objects.all()
    data = set_data("movies", movies)
    return render(request, 'movie/movie_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

@login_required
def movie_save(request):
    name = request.POST['name']
    synopsis = request.POST['synopsis']
    duration = request.POST['duration']
    year = request.POST['year']
    imdb = request.POST['imdb']
    trailerLink = request.POST['trailerLink']
    genre_id = request.POST['genre']
    
    if genre_id =='':
        context["error_message"] = "El genero es obligatorio"
        return render(request, "movie/movie_form.html", context)
    
    if name =='':
        context["error_message"] = "El nombre es obligatorio"
        return render(request, "movie/movie_form.html", context)
    
    genre = Genre.objects.get(pk=genre_id)
    
    movie = Movie(
        name = name, 
        synopsis = synopsis,
        duration = duration, 
        year = year,
        imdb = imdb,
        genre = genre,
        trailerLink = trailerLink
    )
    
    images = request.FILES.getlist('images')
    actor_ids = request.POST.getlist('actors')
    if len(images) < 1:
        context = {"error_message": "Debes minimo 1 imágen.", "genre_list": Genre.objects.all()}
        return render(request, "movie/movie_form.html", context)
    
    movie.save() 
    
    for img in images:
        Image.objects.create(movie=movie, image=img)
    
    for actor_id in actor_ids:
        actor = Actor.objects.get(pk=actor_id)
        ActorMovie.objects.create(actor=actor, movie=movie)

    return redirect("movie:movie_list")

def search_list_view(request):
    query = request.GET.get('q')
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    actors = Actor.objects.all()

    if query:
        movies = movies.filter(name__icontains=query)
        movies_by_genre = Movie.objects.filter(genre__name__icontains=query)
        movies_by_actor = Movie.objects.filter(actormovie__actor__name__icontains=query)
        
        movies = movies | movies_by_genre | movies_by_actor
    
    movies = movies.distinct()
    
    context = {
        'genres': genres,
        'movies': movies,
        'actors': actors,
    }
    
    return render(request, 'movie/index.html', context)    

movie/templates/movie/partials/navbar-client.html
{% load static %}
{% include "movie/partials/styles.html" %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Peliculas</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Por Actor
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for actor in actors %}
                <li><a class="dropdown-item" href="{% url 'movie:movies_by_actor' actor.id %}">{{ actor.name }}, {{actor.last_name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Por Género
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for genre in genres %}
                <li><a class="dropdown-item" href="{% url 'movie:movies_by_genre' genre.id %}">{{ genre.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="btn btn-success" href="{% url 'movie:dashboard' %}" >Dashboard</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex" method="GET" action="{% url 'movie:search_list_view' %}" style="width:500px">
          <input class="form-control me-2" type="search" name="q" placeholder="Buscar pelicula por nombre, actor o genero" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>

        {% if user.is_authenticated %}
        <div class="d-flex mb-3 pl-5">
          <span class ="mt-2"> {{ user.username }} </span>
          <a class="btn btn-light" href="{% url 'movie:logout' %}">Cerrar sesion</a>
        </div>
        {% else %}
        <div class="d-flex mb-3 pl-5">
          <a class="btn btn-light" href="{% url 'movie:login' %}">Login</a>
        </div>    
        {% endif %}
      </div>
    </div>
  </nav>

movie/templates/movie/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movie:movie_list' %}">Peliculas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movie:actors_list' %}">Actores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movie:genre_list' %}">Genero</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="btn btn-success" href="{% url 'movie:index' %}" >Vista Cliente</a>
          </li>
          {% endif %}
        </ul>
        
        <div class="d-flex mb-3 pl-5">
          <a class="btn btn-light" href="{% url 'movie:logout' %}">Cerrar sesion</a>
        </div>
        
      </div>
    </div>
  </nav>
{% include "movie/partials/styles.html" %}

movie/templates/movie/partials/styles.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>