catalog_movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('movie/', include("movie.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name = "movie"
urlpatterns = [
    path("", views.index, name="index" ),
    path("dashboard/", views.my_dashboard, name="dashboard"),
    path("login/", views.my_login, name="login"),
    path("user_login/", views.user_login, name="user_login"),
    path("user_logout/", views.user_logout, name="logout"),
    
    path("genre_list/", views.genre_list_view, name="genre_list"),
    path("actors_list/", views.actor_list_view, name="actors_list"),
    path("movie_list/", views.movie_list_view, name="movie_list"),
    
    path("movie_form/", views.movie_form, name="movie_form"),
    path("genre_form/", views.genre_form, name="genre_form"),
    path("actor_form/", views.actor_form, name="actor_form"),

    path("genre_save/", views.genre_save, name="genre_save"),
    path("movie_save/", views.movie_save, name="movie_save"),
    path("actor_save/", views.actor_save, name="actor_save"),
    
    path('genre/<int:genre_id>/', views.movies_by_genre, name='movies_by_genre'),
    path('actor/<int:actor_id>/', views.movies_by_actor, name='movies_by_actor'),
    
    path("search_list_view/", views.search_list_view, name="search_list_view"),
    
    path('movie/<int:movie_id>/', views.movie_detail_view, name='movie_detail'),
    
    path('movie/<int:movie_id>/like/', views.like_movie, name='like_movie'),
    path('movie/<int:movie_id>/dislike/', views.dislike_movie, name='dislike_movie'),
    
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
class Actor(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Movie(models.Model):
    name = models.CharField(max_length=100)
    synopsis = models.CharField(max_length=250)
    duration = models.IntegerField()
    year = models.IntegerField()
    imdb = models.FloatField()
    trailerLink = models.CharField(max_length=250)
  
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class RateMovieUser(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reaction = models.CharField(max_length=10, choices=[('like', 'Like'), ('dislike', 'Dislike')])
    
    class Meta:
        unique_together = ('user', 'movie')

    def __str__(self):
        return f"{self.user.username} - {self.movie.name} - {self.reaction}"

class ActorMovie(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

class TagMovie(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

class Image(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    

movie/views.py
from django.shortcuts import render

# Create your views here.

movie/views/view_actors.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Actor

@login_required
def actor_form(request):
    return render(request, 'movie/actor_form.html')

def actor_list_view(request):
    actors = Actor.objects.all()
    data = set_data("actors", actors)
    return render(request, 'movie/actor_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

@login_required
def actor_save(request):
    name = request.POST['name']
    last_name = request.POST['last_name']
    age = request.POST['age']
    actor = Actor(name=name, last_name=last_name, age=age)
    actor.save()

    return redirect("movie:actors_list")

movie/views/view_genre.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Genre

@login_required
def genre_form(request):
    return render(request, 'movie/genre_form.html')

@login_required
def genre_save(request):
    name = request.POST['name']
    genre = Genre(name=name)
    genre.save()

    return redirect("movie:genre_list")

def genre_list_view(request):
    genres = Genre.objects.all()
    data = set_data("genres", genres)
    return render(request, 'movie/genre_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

movie/views/view_login.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count, Q
from ..models import Movie, Genre, Actor, RateMovieUser

def my_login(request):
    return render(request, 'movie/login.html')

def my_dashboard(request):
    return render(request, 'movie/dashboard.html')

def user_login(request):
    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect("movie:index")
    else:
        context = {
            "error_message": "Nombre de usuario o contraseña incorrectos."
        }
        return render(request, 'movie:login', context)

def user_logout(request):
    logout(request)
    return redirect('movie:index')

def index(request):
    movies = (Movie.objects
              .prefetch_related('genre', 'actormovie_set', 'image_set')
              .annotate(
                  like_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='like')),
                  dislike_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='dislike'))
              )
              .all())
    genres = Genre.objects.all()
    actors = Actor.objects.all()
    user_reactions=[]
    if request.user.is_authenticated:
     user_reactions = {reaction.movie.id: reaction.reaction for reaction in RateMovieUser.objects.filter(user=request.user)}
    
    context = {
        'genres': genres,
        'movies': movies,
        'actors': actors,
        'user_reactions': user_reactions,
    }
    return render(request, 'movie/index.html',context)

def movie_list_view(request):
    movies = (Movie.objects
              .prefetch_related('genre', 'actormovie_set', 'image_set')
              .annotate(like_count=Count('ratemovieuser', filter=Q(ratemovieuser__reaction='like')))
              .all())
    genres = Genre.objects.all()

    context = {
        'movies': movies,
        'genres': genres,
    }
    return render(request, 'movie/movie_list.html', context)

def movies_by_genre(request, genre_id):
    genre = Genre.objects.get(id=genre_id)
    movies = Movie.objects.filter(genre=genre)

    context = {
        'genre': genre,
        'movies': movies,
    }
    return render(request, 'movie/movies_by_genre.html', context)

def movies_by_actor(request, actor_id):
    actor = Actor.objects.get(id=actor_id)
    movies = Movie.objects.filter(actormovie__actor=actor)

    context = {
        'actor': actor,
        'movies': movies,
    }
    return render(request, 'movie/movies_by_actor.html', context)

def movie_detail_view(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    images = movie.image_set.all()
    actors = movie.actormovie_set.all()

    context = {
        'movie': movie,
        'images': images,
        'actors': actors,
    }

    return render(request, 'movie/movie_detail.html', context)

def like_movie(request, movie_id):
    if request.method == 'POST':
        movie = get_object_or_404(Movie, id=movie_id)
        RateMovieUser.objects.update_or_create(
            user=request.user,
            movie=movie,
            defaults={'reaction': 'like'}
        )
    return redirect('movie:index')

def dislike_movie(request, movie_id):
    if request.method == 'POST':
        movie = get_object_or_404(Movie, id=movie_id)
        RateMovieUser.objects.update_or_create(
            user=request.user,
            movie=movie,
            defaults={'reaction': 'dislike'}
        )
    return redirect('movie:index')

movie/views/view_movies.py
from django.shortcuts import render
from django import forms
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from ..models import Movie, Genre, Image, Actor, ActorMovie

def movies(request):
    movies = Movie.objects.all()
    
    context = {
        "movies": movies
    }
    
    return (render, "movie/movies", context)

@login_required
def save_movie(request):
    return redirect("movie:index")

@login_required
def movie_form(request):
    genres = Genre.objects.all()
    actors = Actor.objects.all() 
    
    context = {
        "genre_list" : genres,
        "actor_list": actors
    }

    return render(request, 'movie/movie_form.html', context)

def movie_list_view(request):
    movies = Movie.objects.all()
    data = set_data("movies", movies)
    return render(request, 'movie/movie_list.html', data)

def set_data(name, data):
    context= {
        name: data
    }
    return context

@login_required
def movie_save(request):
    name = request.POST['name']
    synopsis = request.POST['synopsis']
    duration = request.POST['duration']
    year = request.POST['year']
    imdb = request.POST['imdb']
    trailerLink = request.POST['trailerLink']
    genre_id = request.POST['genre']
    
    if genre_id =='':
        context["error_message"] = "El genero es obligatorio"
        return render(request, "movie/movie_form.html", context)
    
    if name =='':
        context["error_message"] = "El nombre es obligatorio"
        return render(request, "movie/movie_form.html", context)
    
    genre = Genre.objects.get(pk=genre_id)
    
    movie = Movie(
        name = name, 
        synopsis = synopsis,
        duration = duration, 
        year = year,
        imdb = imdb,
        genre = genre,
        trailerLink = trailerLink
    )
    
    images = request.FILES.getlist('images')
    actor_ids = request.POST.getlist('actors')
    if len(images) < 1:
        context = {"error_message": "Debes minimo 1 imágen.", "genre_list": Genre.objects.all()}
        return render(request, "movie/movie_form.html", context)
    
    movie.save() 
    
    for img in images:
        Image.objects.create(movie=movie, image=img)
    
    for actor_id in actor_ids:
        actor = Actor.objects.get(pk=actor_id)
        ActorMovie.objects.create(actor=actor, movie=movie)

    return redirect("movie:movie_list")

def search_list_view(request):
    query = request.GET.get('q')
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    actors = Actor.objects.all()

    if query:
        movies = movies.filter(name__icontains=query)
        movies_by_genre = Movie.objects.filter(genre__name__icontains=query)
        movies_by_actor = Movie.objects.filter(actormovie__actor__name__icontains=query)
        
        movies = movies | movies_by_genre | movies_by_actor
    
    movies = movies.distinct()
    
    context = {
        'genres': genres,
        'movies': movies,
        'actors': actors,
    }
    
    return render(request, 'movie/index.html', context)    

movie/templates/movie/actor_form.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}
<h4> Actor form</h4>

<form action="{% url 'movie:actor_save' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %} <p>{{ error_message }}</p>{% endif %}
        <label for="name">Nombre*: </label>
        <input type="text" name="name" id="name" value="{% if actor %} {{ actor.name}} {% endif %}">
        <label for="name">Apellido*: </label>
        <input type="text" name="last_name" id="last_name" value="{% if actor %} {{ actor.last_name}} {% endif %}">
        <label for="name">Edad: </label>
        <input type="text" name="age" id="age" value="{% if actor %} {{ actor.age}} {% endif %}">
    </fieldset>
    <input class="btn btn-primary" type="submit" value="Guardar">
</form>
<a class="btn btn-danger" href="{% url 'movie:dashboard' %}">Volver</a>

movie/templates/movie/actor_list.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<h4>Actores</h4>
<a class="btn btn-primary" href="{% url 'movie:actor_form' %}">Agregar</a>
<table class="table table-striped table-responsive">
    <thead>
        <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Edad</th>
        </tr>
    </thead>
    <tbody>
        {% for actor in actors %}
        <tr>
        <td>{{ actor.name }}</td>
        <td>{{ actor.last_name }}</td>
        <td>{{ actor.age }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

movie/templates/movie/dashboard.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<h1>Bienvenido</h1>

<button type="button" class="btn btn-primary">Peliculas</button>

movie/templates/movie/genre_form.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<h4> Genre form</h4>

<form action="{% url 'movie:genre_save' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %} <p>{{ error_message }}</p>{% endif %}
        <label for="name">Nombre*: </label>
        <input type="text" name="name" id="name" value="{% if genre %} {{ genre.name}} {% endif %}">
    </fieldset>
    <input class="btn btn-primary" type="submit" value="Guardar">
</form>
<a class="btn btn-danger" href="{% url 'movie:dashboard' %}">Volver</a>

movie/templates/movie/genre_list.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<h4>Genero</h4>
<a class="btn btn-primary" href="{% url 'movie:genre_form' %}">Agregar</a>

<table class="table table-striped table-responsive">
    <thead>
        <tr>
        <th scope="col">Nombre</th>
        </tr>
    </thead>
    <tbody>
        {% for genre in genres %}
        <tr>
        <td>{{ genre.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

movie/templates/movie/index.html
{% include "movie/partials/navbar-client.html" %}
{% load custom_filters %}
<div class="container-fluid">
  <div class="row row-cols-1 row-cols-md-6 g-4">
    {% for movie in movies %}
    <div class="col">
        <div class="card" class="heigth:10px">
          {% with movie.image_set.first as first_image %}
            {% if first_image %}
                <img src="{{ first_image.image.url }}" alt="Imagen de {{ movie.name }}" />
            {% else %}
                <li>No hay imágenes disponibles.</li>
            {% endif %}
        {% endwith %}
          <div class="card-body">
            <h5 class="card-title">{{ movie.name }}</h5>
            <p class="card-text" style="'width':'200px';'overflow': 'hidden';">{{ movie.synopsis }}</p>
          <div class="row">
            <div class="col-5">
              <h6 class="card-title">Genero: 
                <a class="dropdown-item" href="{% url 'movie:movies_by_genre' movie.genre.id %}">    
                  <span class="badge text-bg-danger">  
                    {{movie.genre.name}} 
                  </span>
                </a>
              </h6>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2 2 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a10 10 0 0 0-.443.05 9.4 9.4 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a9 9 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.2 2.2 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.9.9 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
              </svg>
              {{ movie.like_count }}
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856s-.036.586-.113.856c-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a10 10 0 0 1-.443-.05 9.36 9.36 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a9 9 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581s-.027-.414-.075-.581c-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.2 2.2 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.9.9 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1"/>
              </svg>
              {{ movie.dislike_count }}
            </div>
            <div class="col-7">
              <div class="mb-2">
                <h6>Reparto:</h6>
                {% for actor_movie in movie.actormovie_set.all %}
                <a class="dropdown-item" href="{% url 'movie:movies_by_actor' actor_movie.actor.id %}">    
                    <span class="badge text-bg-success">  
                      {{ actor_movie.actor.name }}, {{ actor_movie.actor.last_name }}
                    </span>
                </a>
                {% endfor %}
              </div>
            </div>
            {% if user.is_authenticated %}
                Te gustó?
                <div class="row">
                    <div class="col-3">
                        <form action="{% url 'movie:like_movie' movie.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-sm">Sí</button>
                        </form>
                    </div>
                    <div class="col-4">
                        <form action="{% url 'movie:dislike_movie' movie.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">No</button>
                        </form>
                    </div>
                </div>
            {% else %}
                <p>Debes estar logueado <a href="{% url 'movie:login' %}">Inicia sesión</a></p>
            {% endif %}
          </div>
            <a href="{% url 'movie:movie_detail' movie.id %}" class="btn btn-primary">Ver Detalle</a>
          </div>
        </div>
      </div>
    {% endfor %}  
  </div>
</div>

movie/templates/movie/login.html
{% include "movie/partials/styles.html" %}

<div class="d-flex align-items-center py-4 bg-body-tertiary">
    <div class="form-signin w-100 m-auto">
        <div class="offset-3 col col-4 mt-5">
            <form action="{% url 'movie:user_login' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend><h2>Login</h2></legend>
                    {% if error_message %} <p>{{ error_message }}</p> {% endif %}
                    <label for="username">Usuario:</label>
                    <input class="form-control" type="text" name="username" id="username" />
                    <label for="password">Password:</label>
                    <input class="form-control" type="password" name="password" id="password" />
                </fieldset>
                <input class="btn btn-primary" type="submit" value="Ingresar" />
            </form>
        </div>
    </div>
</div>

movie/templates/movie/movie_detail.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar-client.html" %}

    <div class="container">
        <h1>{{ movie.name }}</h1>
        <div class="row">
            <div class="col-4">
                <p><strong>Sinopsis:</strong> {{ movie.synopsis }}</p>
                <p><strong>Año:</strong> {{ movie.year }}</p>
                <p><strong>Duración:</strong> {{ movie.duration }} minutos</p>
                <p><strong>IMDB:</strong> {{ movie.imdb }}</p>
                <p><strong>Genero:</strong> {{ movie.genre.name }}</p>
            </div>
            <div class="col-8">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/{{movie.trailerLink|slice:'-11:'}}" 
                frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowfullscreen></iframe>
            </div>
        </div>
        
        <h2>Imágenes</h2>
        <div class="row">
            {% for image in images %}
                <div class="col-md-2">
                    <img src="{{ image.image.url }}" alt="Imagen de {{ movie.name }}" class="img-fluid">
                </div>
            {% empty %}
                <p>No hay imágenes disponibles.</p>
            {% endfor %}
        </div>

        <h2>Reparto</h2>
        <div>
            {% for actor_movie in actors %}
            <a class="dropdown-item" href="{% url 'movie:movies_by_actor' actor_movie.actor.id %}">
                <span class ="badge text-bg-danger">{{ actor_movie.actor.name }} {{ actor_movie.actor.last_name }}</span>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
            </a>
        </div>

        <a href="{% url 'movie:index' %}" class="btn btn-primary mt-3">Volver</a>
    </div>

movie/templates/movie/movie_form.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<div class="container">
    <h4>Crear Pelicula</h4>

    <form action="{% url 'movie:movie_save' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {% if error_message %} <p style="color:red">{{ error_message }}</p>{% endif %}

            <label for="type">Genero</label>
            <select class="form-control" name="genre" id="genre" required>
                <option value="" selected>----</option>
                {% if genre_list %}
                    {% for genre in genre_list %}
                        <option value="{{ genre.id }}">{{ genre.name }}</option>
                    {% endfor %}
                {% endif %}
            </select>
            <label for="type">Reparto</label>
            <select class="form-control" name="actors" multiple required>
                {% for actor in actor_list %}
                    <option value="{{ actor.id }}">{{ actor.name }},  {{ actor.last_name }}</option>
                {% endfor %}
            </select>

            <label for="name">Nombre*: </label>
            <input  class="form-control" type="text" name="name" id="name" value="{% if movie %} {{ movie.name}} {% endif %}" required>
            <label for="sinopsis">Sinopsis*: </label>
            <input class="form-control" type="text" name="synopsis" id="synopsis" value="{% if movie %} {{ movie.synopsis}} {% endif %}" required>
            <label for="duration">Duration*: </label>
            <input class="form-control" type="number" name="duration" id="duration" value="{% if movie %} {{ movie.duration}} {% endif %}" required>
            <label for="year">Anio*: </label>
            <input class="form-control" type="number" name="year" id="year" value="{% if movie %} {{ movie.year}} {% endif %}" required>
            <label for="imdb">Imdb*: </label>
            <input class="form-control" type="number" name="imdb" id="imdb" value="{% if movie %} {{ movie.imdb}} {% endif %}" required>
            <label for="trailerLink">TrailerLink*: </label>
            <input class="form-control" type="text" name="trailerLink" id="trailerLink" value="{% if movie %} {{ movie.trailerLink}} {% endif %}" required>
        </fieldset>

        <h3>Subir imágenes (mínimo 1):</h3>
        <input class="form-control"  type="file" name="images" multiple required>

        <input class="btn btn-primary" type="submit" value="Guardar">
    </form>

<a class="btn btn-danger" href="{% url 'movie:index' %}">Volver</a></div>

movie/templates/movie/movie_list.html
{% include "movie/partials/styles.html" %}
{% include "movie/partials/navbar.html" %}

<div class="container">
<h4>Peliculas</h4>
<a class="btn btn-primary" href="{% url 'movie:movie_form' %}">Agregar</a>
<table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Sinopsis</th>
        <th scope="col">Duracion</th>
        <th scope="col">Año</th>
        <th scope="col">Imdb</th>
        <th scope="col">Url Video</th>
        <th scope="col">Genero</th>
      </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
      <tr>
        <td>{{ movie.name }}</td>
        <td>{{ movie.synopsis }}</td>
        <td>{{ movie.duration }} (m)</td>
        <td>{{ movie.year }}</td>
        <td>{{ movie.imdb }}</td>
        <td>{{ movie.trailerLink }}</td>
        <td>{{ movie.genre.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

movie/templates/movie/movies_by_actor.html
{% include "movie/partials/navbar-client.html" %}

<div class="container-fluid">
    <h1>Películas de {{ actor.name }}, {{actor.last_name}}</h1>
    <ul>
        {% for movie in movies %}
            <li>
                <h3>{{ movie.name }}</h3>
                <p>{{ movie.synopsis }}</p>
                <p>Año: {{ movie.year }}</p>
            </li>
        {% empty %}
            <li>No hay películas disponibles en este género.</li>
        {% endfor %}
    </ul>
    
    <a class="btn btn-secondary" href="{% url 'movie:index' %}">Volver</a>
</div>

movie/templates/movie/movies_by_genre.html
{% include "movie/partials/navbar-client.html" %}

<div class="container-fluid">
    <h1>Películas de {{ genre.name }}</h1>
    <ul>
        {% for movie in movies %}
            <li>
                <h3>{{ movie.name }}</h3>
                <p>{{ movie.synopsis }}</p>
                <p>Año: {{ movie.year }}</p>
            </li>
        {% empty %}
            <li>No hay películas disponibles en este género.</li>
        {% endfor %}
    </ul>
    <a class="btn btn-secondary" href="{% url 'movie:index' %}">Volver</a>
</div>